.gitignore
.travis.yml
tests/__init__.py
tests/unit/test_json.py

*Description of changes:* Adds a Travis CI integration, which runs unit tests on the repo. To start, it will verify that `manifest.json` is a valid JSON file, since any change which breaks this assumption would cause a disruption to `sam init` function.

Add JSON Validation Check

---

manifest.json
ruby2.7/cookiecutter-aws-sam-hello-ruby/.gitignore
ruby2.7/cookiecutter-aws-sam-hello-ruby/README.md
ruby2.7/cookiecutter-aws-sam-hello-ruby/cookiecutter.json
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/.gitignore
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/Gemfile
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/README.md
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/events/event.json
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/hello_world/Gemfile
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/hello_world/app.rb
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/template.yaml
ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/tests/unit/test_handler.rb

Why is this change necessary?
* `sam init` does not yet have support ruby2.7 init templates.
How does it address the issue?
* `sam init` interactively pulls from a github repo for init projects
based on runtime and other selections.
What side effects does this change have?
* None

feat: ruby 2.7 templates for `sam init`

---

go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/hello-world/go.mod

Why is this change necessary?
* `sam build` fails with Error: GoModulesBuilder:Build - Builder Failed: can't load package: package /Users/localuser/workspace/apps/go-1.x/hello-world: import "/Users/localuser/workspace/apps/go-1.x/hello-world": cannot import absolute path
How does it address the issue?
* Adds the necessary `go.mod` file
What side effects does this change have?
* None

fix: add go.mod for the go sam init templates

---

go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/README.md

Current golang readme is mentioning python runtime instead of golang. Small fix to correct it.

Fixed golang readme mentioning python runtime

---

nodejs10.x/cookiecutter-quick-start-sns/{{cookiecutter.project_name}}/template.yml
nodejs12.x/cookiecutter-quick-start-sns/{{cookiecutter.project_name}}/template.yml

*Issue* 
SAM deploy of this quick start fails with the exception  'An ARN must have at least 6 elements, not 3'
As per the[ AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html)  Fn::GetAtt SimpleTopic only returns the 'Topic name' and not an ARN. This must be replaced by the !Ref intrinsic function which returns the ARN to deploy successfully

Fix Topic Arn reference from GetAtt to !Ref

---

buildspecs/buildspec-unittest-python2.7.yml

Same as #82, pip drops python 2 support, we need to install an old version.

ci: Fix Python2.7 template unit test fails in CI due to pip dropping support

---

dotnetcore3.1-image/cookiecutter-aws-sam-hello-dotnet-lambda-image/{{cookiecutter.project_name}}/template.yaml
dotnetcore3.1/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml

n/a
The template.yaml for the dotnetcore3.1 'Hello World' samples don't specify the function memory size, so the default of 128MB applies. However, when making even small changes, I found myself getting errors. It took forever to figure out that this was because the memory size was too small.
This PR adds a line to the template.yaml for the HelloWorld samples (ZIP and container image) to specify the memory size as 256. This resolves the above issue, makes the functions start faster, and also is consistent with the 'aws-lambda-tools-defaults.json' file that is already in each project.

Changed dotnetcore3.1 HelloWorld samples to 256MB

---

buildspec.yml
buildspecs/buildspec-unittest-java8.yml

aws/codebuild/standard:3.0 is no longer maintained after May 2021. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

ci: Use standard:5.0 for java 8

---

ruby2.5-image/cookiecutter-aws-sam-hello-ruby-lambda-image/{{cookiecutter.project_name}}/hello_world/Dockerfile
ruby2.7-image/cookiecutter-aws-sam-hello-ruby-lambda-image/{{cookiecutter.project_name}}/hello_world/Dockerfile

This change sets the `GEM_HOME` environment variable before running `bundle install` in order to ensure that Gems are installed under `${LAMBDA_TASK_ROOT}` so that they are discoverable by the Lambda Ruby Runtime.
1. Create a Ruby 2.5 or 2.7 image project using the `sam init` "hello world" template
2. Uncomment `require 'httparty'` from `hello_world/app.rb`
3. Build and invoke the image locally with `sam build && sam local invoke`
This will throw an error similar to:
```
START RequestId: 7e3782c6-fb15-44e2-8c68-d466f700ee0d Version: $LATEST
Init error when loading handler app.lambda_handler
{
"errorMessage": "cannot load such file -- httparty",
"errorType": "Init<LoadError>",
"stackTrace": [
"/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'", …
```

Set GEM_HOME in Ruby runtimes' image Dockerfile templates

---

python3.8-image/cookiecutter-ml-apigw-tensorflow/{{cookiecutter.project_name}}/app/requirements.txt

chore: Bump Python 3.8 ML APIGW Tensorflow to 2.5.1

---

java11-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java11-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java11/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java11/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8.al2-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8.al2-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8.al2/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8.al2/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
java8/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java

argument orders in assertEquals in the testing code are fixed. Formerly, they reported assertion errors like "expected:<500> but was:<200>"

fix: argument orders in assertEquals

---

nodejs12.x/cookiecutter-quick-start-cloudwatch-events/README.md
nodejs12.x/cookiecutter-quick-start-from-scratch/README.md
nodejs12.x/cookiecutter-quick-start-s3/README.md
nodejs12.x/cookiecutter-quick-start-sns/README.md
nodejs12.x/cookiecutter-quick-start-sqs/README.md
nodejs12.x/cookiecutter-quick-start-web/README.md
nodejs12.x/cookiecutter-typescript-app-template/README.md
nodejs14.x/cookiecutter-quick-start-cloudwatch-events/README.md
nodejs14.x/cookiecutter-quick-start-from-scratch/README.md
nodejs14.x/cookiecutter-quick-start-s3/README.md
nodejs14.x/cookiecutter-quick-start-sns/README.md
nodejs14.x/cookiecutter-quick-start-sqs/README.md
nodejs14.x/cookiecutter-quick-start-web/README.md

Noticed a few readmes with incorrect command line argument changed --application-template to --app-template in readme

correct --application-template to --app-template in readme

---

go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/README.md

https://github.com/aws/aws-sam-cli-app-templates/issues/149
*Description of changes:* Go uses `go` instead of a Makefile.
Match `go1.x` README to directory structure.

docs: go1.x README

---

buildspecs/buildspec-unittest-python3.6.yml

CodeBuild CI is broken due to unable to get get-pip.py for 3.6.
Changed URL in 3.6 build.spec to download the older version.

fix: Set get-pip URL to 3.6

---

manifest.json

Modify the basic template for .NET6 to show up as "Hello World Example" instead of "Serverless API"
Testing `sam init` locally with this new version:
```
$ samdev init
You can preselect a particular runtime or package type when using the `sam init` experience.
Call `sam init --help` to learn more.
Which template source would you like to use?
1 - AWS Quick Start Templates
2 - Custom Template Location
Choice: 1
Choose an AWS Quick Start application template
1 - Hello World Example
2 - Multi-step workflow
3 - Serverless API
4 - Scheduled task
5 - Standalone function
6 - Data processing
7 - …
```

fix(dotnet6): Set .NET6 example as Hello-World

---

manifest-v2.json

fix: add nodejs16 image type to the manifest

---

.github/workflows/manifest-v2-check.yml
manifest-v2.json

Earlier PR have changed manifest-v2.json file which then affected SAM CLI by failing to parse it. 
This PR is addressing that issue as well as adding a GH action to validate this forward.
Invalid manifest run: https://github.com/mndeveci/aws-sam-cli-app-templates/runs/6397633007?check_suite_focus=true
Valid manifest run: https://github.com/mndeveci/aws-sam-cli-app-templates/runs/6397687402?check_suite_focus=true

fix: fix manifest-v2.json file and add GH action to validate this from now on

---

.github/ISSUE_TEMPLATE/anything_else.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md
.github/workflows/pr-labeler.yml

Will help triage which new issues and PRs haven't been looked at by the team, as querying by no comments or no labels can sometimes be misleading.
New label stage/needs-triage automatically assigned on new issues and PRs.

feat: improve new PR and issue labeling for triaging

---

provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-maven/{{cookiecutter.project_name}}/Dockerfile
provided.al2/graalvm/java17/cookiecutter-aws-sam-graalvm-maven/{{cookiecutter.project_name}}/Dockerfile

`https://dlcdn.apache.org/maven/maven-3/${MVN_VERSION}/binaries/${MVN_FILENAME}` is now 404 for `3.8.5`. As shown in https://dlcdn.apache.org/maven/maven-3/, only `3.8.6` is available. 
Example of error:
```
----------------------------- Captured stderr call -----------------------------
Temporary directory /tmp/tmpgw_dpx4t created
['sam', 'init', '--no-input', '--location', PosixPath('/codebuild/output/src339179747/src/github.com/aws/aws-sam-cli-app-templates/provided.al2/graalvm/java17/cookiecutter-aws-sam-graalvm-maven'), '--name', 'project']
PATH=/root/.pyenv/versions/3.9.12/bin:/root/.pyenv/libexec:/root/.pyenv/plugins/python-build/bin:/root/.pyenv/plugins/pyenv-virtualenv/bin:/root/.pyenv/plugins/pyenv-update/bin:/root/.pyenv/plugins/pyenv-installer/bin:/root …
```

Bump maven version in Graavlm Maven dockerfile from 3.8.5 to 3.8.6

---

manifest-v2.json

In the Python 3.8 and Python 3.9 examples, the EFS example is incorrectly named as 'Serverless API'. I've updated the name of these two examples to 'Lambda EFS example' in the manifest file.

Rename Python 3.8 and 3.9 EFS example

---

dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Program.cs

*Issue #, if available:* N/A
- Update a template comment. Previously a comma between "Lambda" and "Kestrel" would've helped with readability. New wording borrowed from [an AWS blog post](https://aws.amazon.com/blogs/developer/running-serverless-asp-net-core-web-apis-with-amazon-lambda/)

docs: Improve "dotnet quick start web" comment

---

go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/events/event.json

The `event.json` file is missing from the golang, hello world example. This means developers won't have a base event file to do local testing with. 
I copied the python `/python3.9/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/events/event.json` file and placed it in the appropriate place for the golang hello world app.

fix: adding missing event.json file for golang hello world example.

---

python3.8-image/cookiecutter-ml-apigw-pytorch/{{cookiecutter.project_name}}/template.yaml
python3.8-image/cookiecutter-ml-apigw-scikit-learn/{{cookiecutter.project_name}}/template.yaml
python3.8-image/cookiecutter-ml-apigw-tensorflow/{{cookiecutter.project_name}}/template.yaml
python3.8-image/cookiecutter-ml-apigw-xgboost/{{cookiecutter.project_name}}/template.yaml
python3.9-image/cookiecutter-ml-apigw-pytorch/{{cookiecutter.project_name}}/template.yaml
python3.9-image/cookiecutter-ml-apigw-scikit-learn/{{cookiecutter.project_name}}/template.yaml
python3.9-image/cookiecutter-ml-apigw-tensorflow/{{cookiecutter.project_name}}/template.yaml
python3.9-image/cookiecutter-ml-apigw-xgboost/{{cookiecutter.project_name}}/template.yaml

Looks like the attribute name for the deployed iam role resource is wrong on the python 3.8/3.9 ml cookiecutter templates. 

fix function iam role attribute name for python 3.8/9 ml templates

---

nodejs14.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
nodejs14.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml

- Set source map environment variable so that it's configured correctly out-of-the-box.
- Move esbuild to be a non-dev dependency since esbuild will be using the npm install production flag and dev dependencies will no longer be installed.

feat: Update esbuild templates to match GA changes

---

nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/app.ts
nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/app.ts

Very helpful type for handling exceptions. Now you can easily use `throw new Error("some error message")` to provide more descriptive messages for your consumers.

Add unknown type for try catch section in TypeScript templates

---

nodejs14.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml

Since source maps generate an environment variable which requires the deployment role to have KMS:Encrypt as a policy, let's disable this in the template by default and make it opt-in.

Disable sourcemaps by default

---

provided.al2/rust/cookiecutter-aws-sam-hello-rust/{{ cookiecutter.project_slug }}/Cargo.toml
provided.al2/rust/cookiecutter-aws-sam-hello-rust/{{ cookiecutter.project_slug }}/Makefile
provided.al2/rust/cookiecutter-aws-sam-hello-rust/{{ cookiecutter.project_slug }}/README.md
provided.al2/rust/cookiecutter-aws-sam-hello-rust/{{ cookiecutter.project_slug }}/src/main.rs

*Issue #, if available:* #267 
This fixed bug #267. It also updates the dependencies to the latest version. It also fixes some trait mismatch bug in `src/main.rs` because of the lambda-http upgrade.

Fixed #267 - Upgrade rust template dependencies and fixed makefile

---

nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/app.ts

Issue #, if available: N/A
Rationale behind the change:
- Developers will likely copy and modify the hello world template when using creating a new project. The error would be logged at an incorrect level if an error is thrown in a real world project without anyone changing the template catch block code.
Description of changes:
- Change the hello world typescript handler to use console.error instead of console.log when an error is thrown.

Update hello world ts to use correct error logging

---

.github/workflows/manifest-backward-compability-check.yml

- always check for backward incompatibility.

fix: non-custom GH action for `manifest.json`

---

.github/ISSUE_TEMPLATE/bug_report.md

N/A
Main reason is for how we track bugs. We first want to validate the bug before adding the label.

chore: Remove type/bug label for Bug Issue Template

---

manifest-v2.json

*Issue #, if available:* #354
This PR fixes .NET and TypeScript templates `useCaseName` field to sync with Python and Java templates. I also took liberty to sync `displayName` field.

chore(manifest): sync powertools examples useCaseName/displayName

---

python3.7/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile
python3.8/apigw-pytorch/{{cookiecutter.project_name}}/app/Dockerfile
python3.8/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
python3.8/apigw-tensorflow/{{cookiecutter.project_name}}/app/Dockerfile
python3.8/apigw-xgboost/{{cookiecutter.project_name}}/app/Dockerfile
python3.8/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile
python3.9/apigw-pytorch/{{cookiecutter.project_name}}/app/Dockerfile
python3.9/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
python3.9/apigw-tensorflow/{{cookiecutter.project_name}}/app/Dockerfile
python3.9/apigw-xgboost/{{cookiecutter.project_name}}/app/Dockerfile
python3.9/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile

*Issue:* #242 
Take advantage of Docker layers to optimize container images for Python

Optimize docker images for python

---

.github/workflows/build_test_invoke.yml

Once build image is published, we can merge this PR to enable build & invoke tests for python3.10

fix: add py3.10 tests back

---

dotnetcore3.1/s3/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/FunctionTest.cs
dotnetcore3.1/s3/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj
tests/integration/unit_test/test_unit_test_dotnetcore3_1.py

*Issue:*  #195 
Mock S3 response for unit testing, avoid creating S3 bucket. The current way is supposed to be integration testing rather than init testing of a code block.

Mock S3 response for unit test

---

manifest-v2.json

https://github.com/aws/aws-sam-cli-app-templates/issues/367
Use a correct app template name for the rust dynamo db template.

fix: use correct app template name for the rust dynamo db template

---

.github/workflows/build_test_invoke.yml

Enable GHA CI jobs to run against `develop` and `feat*` branches.

ci: add feat* rule to run github actions

---

dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
dotnet6/hello-pt/{{cookiecutter.project_name}}/template.yaml

Update Powertools template to v 1.0.1
Removed Common package because it is not needed
Removed TracingEnabled: true from Globals in the template. This property was failing on Sam cli. Still present in the function.

update powertools to v1.0.1

---

al2/rust/hello/{{ cookiecutter.project_slug }}/rust_app/src/main.rs

No issue, just a small fix to remove unused code.
I removed the Body struct from the hello world Rust example because it is not used.

Unused Body struct removed from the hello world Rust example

---

python3.10/apigw-pytorch/cookiecutter.json
python3.10/apigw-scikit/cookiecutter.json
python3.10/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
python3.8/apigw-pytorch/cookiecutter.json
python3.8/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt
python3.9/apigw-pytorch/cookiecutter.json
tests/integration/build_invoke/python/test_python_3_10.py
tests/integration/build_invoke/python/test_python_3_8.py
tests/integration/build_invoke/python/test_python_3_9.py

N/A
The incorrect `torchvision` version was being used with pytorch. This also adds those templates to the build and invoke test suite.

fix: Bump torchvision and added build tests

---

python3.8/apigw-pytorch/cookiecutter.json
python3.8/apigw-pytorch/{{cookiecutter.project_name}}/README.md
python3.8/apigw-scikit/cookiecutter.json
python3.8/apigw-scikit/{{cookiecutter.project_name}}/README.md
python3.8/apigw-tensorflow/cookiecutter.json
python3.8/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
python3.8/apigw-xgboost/cookiecutter.json
python3.8/apigw-xgboost/{{cookiecutter.project_name}}/README.md
python3.8/efs/cookiecutter.json
python3.8/efs/{{cookiecutter.project_name}}/README.md
python3.8/event-bridge-schema/cookiecutter.json
python3.8/event-bridge-schema/{{cookiecutter.project_name}}/README.md
python3.8/event-bridge/cookiecutter.json
python3.8/event-bridge/{{cookiecutter.project_name}}/README.md
python3.8/hello-img/cookiecutter.json
python3.8/hello-img/{{cookiecutter.project_name}}/README.md
python3.8/hello-pt/cookiecutter.json
python3.8/hello-pt/{{ cookiecutter.project_name }}/README.md
python3.8/hello/cookiecutter.json
python3.8/hello/{{cookiecutter.project_name}}/README.md
python3.8/step-func-conn/cookiecutter.json
python3.8/step-func-conn/{{cookiecutter.project_name}}/README.md
python3.8/step-func/cookiecutter.json
python3.8/step-func/{{cookiecutter.project_name}}/README.md
python3.8/web-conn/cookiecutter.json
python3.8/web-conn/{{cookiecutter.project_name}}/README.md

*Issue:* Since this one is minor, I didn't create an issue for this
Changes focus on making bash scripts in Python documentation more consistent. Separated from #385, similar to #406.
There are a few changes included in this PR:
1. Remove hard-coded folder names:
```bash
my-application$ sam build
{{ cookiecutter.project_name }}$ sam build
```
2. Introduce a new private variable for stack name as it turns out wrapping stack name within double quote might not solve the problem of Project Name with white space
`cookiecutter.json`
```
{
"project_name": "Name of the project",
....
"__stack_name": "{{ cookiecutter.project_name.lower().replace(' ', '-') }}"
}
```
For example, if the project name is 'Sam App', stack name will be 'sam-app'
Similar examples can be found in …

Make bash scripts for Python 3.8 projects more consistent

---

dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj

Update dotnet6 Powertools template 1.2.0
Logging and tracing to version 1.1.0
Metrics to version 1.2.0

Update dotnet6 Powertools template 1.2.0

---

nodejs18.x/hello-ts-pt/{{cookiecutter.project_name}}/template.yaml

https://github.com/aws/aws-sam-cli/issues/5319
Typo in the cookiecutter template results in `sam init` crashing when attempting to resolve the template.

fix: Node.js Powertools Template Typo

---

nodejs18.x/s3/{{cookiecutter.project_name}}/package.json
tests/integration/unit_test/unit_test_base.py

Remove the vulnerabilities check from the Nodejs Test cases to fix the failing test cases due to some issue found in one of the dependency. We will depend on Github Dependent bot to upgrade the dependencies as we do in other runtimes templates.

chore: remove the vulnerabilities check from nodejs test cases

---

al2/go/hello-img/tests/test_bake_project.py
al2/go/hello-img/{{cookiecutter.project_name}}/README.md
al2/go/hello-img/{{cookiecutter.project_name}}/hello-world/main.go
al2/go/hello-img/{{cookiecutter.project_name}}/hello-world/main_test.go
al2/go/hello/tests/test_bake_project.py
al2/go/hello/{{cookiecutter.project_name}}/README.md
al2/go/hello/{{cookiecutter.project_name}}/hello-world/main.go
al2/go/hello/{{cookiecutter.project_name}}/hello-world/main_test.go
go1.x/hello-img/tests/test_bake_project.py
go1.x/hello-img/{{cookiecutter.project_name}}/README.md
go1.x/hello-img/{{cookiecutter.project_name}}/hello-world/main.go
go1.x/hello-img/{{cookiecutter.project_name}}/hello-world/main_test.go
go1.x/hello/tests/test_bake_project.py
go1.x/hello/{{cookiecutter.project_name}}/README.md
go1.x/hello/{{cookiecutter.project_name}}/hello-world/main.go
go1.x/hello/{{cookiecutter.project_name}}/hello-world/main_test.go

https://github.com/aws/aws-sam-cli-app-templates/issues/421
Update the Go hello-world example so that it does not rely on an external API call. The call to `https://checkip.amazonaws.com` would intermittently fail and result in unexpected errors. These changes simplify the example and get the requestor's IP from the request context.

Update the Go Hello-World Example

---

python3.10/step-func-conn/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.10/step-func/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.7/step-func-conn/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.7/step-func/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.8/step-func-conn/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.8/step-func/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.9/step-func-conn/{{cookiecutter.project_name}}/tests/unit/test_checker.py
python3.9/step-func/{{cookiecutter.project_name}}/tests/unit/test_checker.py

N/A
Changing `assert 0 <= data["stock_price"] > 0 <= 100` to `assert 0 <= data["stock_price"] <= 100` as the `> 0` part seems redundant.

chore: fix a non-readable syntax in python templates

---

python3.10/apigw-scikit/cookiecutter.json
python3.11/apigw-scikit/cookiecutter.json
python3.8/apigw-scikit/{{cookiecutter.project_name}}/app/requirements.txt
python3.9/apigw-scikit/cookiecutter.json

N/A
Updates outdated version of scikit-learn causing pip installations to fail.

fix: Scikit learn installation

---

java11/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
java17/hello-pt-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
java17/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
java8/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java

*Issue #, if available:* closes #366
This PR adds an explicit parameter `App.class` to the Powertools for AWS Lambda (Java) Logger class. When troubleshooting the dependencies between SAM and CDK bundling we found out that this was the crucial part. To keep the code consistent between CDK and SAM examples we propose to add an explicit param. 
@jeromevdl wrote an extensive [blog post](https://awstip.com/packaging-deploying-java11-based-lambda-functions-19c456e062a9) diving deep into this issue 
I can't believe I missed to close this issue back in March, sorry about that.

improvement: add class param to java powertools logger

---

manifest-v2.json

Powertools init templates have inconsistent examples causing a confusing display screen for identical templates.

Fix Powertools Init Template Naming

---

dotnet6/s3/{{cookiecutter.project_name}}/template.yaml
nodejs14.x/s3/{{cookiecutter.project_name}}/template.yaml
nodejs16.x/s3/{{cookiecutter.project_name}}/template.yaml
nodejs18.x/full-stack/{{cookiecutter.project_name}}/template.yaml
nodejs18.x/s3/{{cookiecutter.project_name}}/template.yaml

Enable Encryption and Versioning for S3 Bucket resources defined in SAM CLI Templates.

fix: enable encryption and versioning for S3 buckets defined in app templates

---

dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/Function.cs
dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj

Update Powertools dotnet6 template versions with new versions from release 1.7.0
Also took the opportunity to update Amazon.Lambda.Serialization.SystemTextJson and Amazon.Lambda.APIGatewayEvents

chore: Update Powertools dotnet6 template v1.7.0

---

python3.8/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt

None.
Bumps the pinned version of `pytorch` for the Python 3.8 runtime.

chore: Bump pillow to 10.1.0 for py3.8 pytorch project

---

.github/workflows/build_test_invoke.yml

None.
Bumps the minimum version of Python that is used to install SAM CLI from source in the actions.

chore: Bump SAM CLI install version for Actions

---

nodejs18.x/full-stack/{{cookiecutter.project_name}}/deploy_frontend.sh

Fixes: https://github.com/aws/aws-sam-cli/issues/5940 Script was failing for MacOS's default grep command
Replace `grep` with aws cli's builtin `query` as `-P` regex in grep is not supported by MacOS

Replace failing grep with builtin query

---

python3.10/apigw-pytorch/{{cookiecutter.project_name}}/app/Dockerfile
python3.10/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
python3.10/apigw-tensorflow/{{cookiecutter.project_name}}/app/Dockerfile
python3.10/apigw-xgboost/{{cookiecutter.project_name}}/app/Dockerfile
python3.10/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile
python3.11/apigw-pytorch/{{cookiecutter.project_name}}/app/Dockerfile
python3.11/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
python3.11/apigw-tensorflow/{{cookiecutter.project_name}}/app/Dockerfile
python3.11/apigw-xgboost/{{cookiecutter.project_name}}/app/Dockerfile
python3.11/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile

Fixes #460 
I'm not sure if I should copy models before app.py, or app.py first. It probably doesn't matter. (Models is larger. But does it change more often?)
Note that I haven't tested these changes, because they're simple. I'm assuming CICD will tell me if I've broken stuff.

Cache pip install in python Dockerfiles

---

go1.x/hello/{{cookiecutter.project_name}}/template.yaml

`tests/end_to_end/test_runtimes_e2e.py::TestHelloWorldZipPackagePermissionsEndToEnd_0_go1_x::test_hello_world_workflow` test is flaky only on windows canaries but is not reproducible on windows VMs, and we cannot determine the root cause. 
Temporarily bumping the timeout from 5s to 10s for a week before go1.x is deprecated to see if that changes anything.

Temporarily bump timeout for flaky test

---

python3.8/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt

https://github.com/aws/aws-sam-cli-app-templates/security/dependabot/235
Pillow has a CVE with version 10.1.0. I checked in our repo and our pillow dependencies are all not fixed or 10.2.0 which is patched except for one runtime, Python3.8. I think we can bump this version because I see in the [Pillow docs](https://pillow.readthedocs.io/en/stable/installation.html) that 10.2.0 is supported or Python3.8

Update Pillow version due to CVE with 10.1

---

nodejs16.x/step-func-conn/{{cookiecutter.project_name}}/makefile
nodejs16.x/step-func/{{cookiecutter.project_name}}/makefile
nodejs18.x/step-func/{{cookiecutter.project_name}}/makefile
nodejs20.x/step-func/{{cookiecutter.project_name}}/makefile

Related to #346
Changes made in #346 created the mocked.test.asl.json file appropriately, but did not use it for the `aws stepfunctions create-state-machine --definition` argument. This PR updates the node v16/18/20 step-func makefiles to do so. 

Update Node makefile create targets to use mock asl definition for testing

---

ruby/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile

None
A recent change to a downstream dependency of `httparty` (`multi_xml>=0.7.0`) now requires build tools to be installed inside of the image. In preparation of `bigdecimal` (another package, this time `multi_xml` requires) not being included in the Ruby 3.4 release, `multi_xml` adds `bigdecimal` explicitly as a dependency requiring a build.
We don't have build tools installed in the image. This fix changes the Dockerfile to adopt our build images to build the extension from source, then utilize the emulation runtime to run the Ruby function.

fix: Use the SAM build images to build image based Ruby functions

---

nodejs20.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/package.json

*Issue #, if available:* N/A
Fixing what appears to be a typo in the `package.json` of the NodeJS 20 Hello Lambda TypeScript with PowerTools template.  I do not see a test case for this one, but I validated that the changes make it so the `package.json` parses and `npm install` works.

fix: Typo in nodejs20 hello-ts-pt package.json

---

tests/integration/build_invoke/python/test_python_3_8.py
tests/integration/unit_test/test_unit_test_python3_8.py

Remove lint tests for python3.8 to unblock GH action tests.

chore: Remove lint tests for python3.8

---

.github/workflows/build_test_invoke.yml
manifest-v2.json
ruby/hello-img/cookiecutter.json
ruby/hello/cookiecutter.json
ruby/step-func/cookiecutter.json
ruby/web/cookiecutter.json
tests/integration/build_invoke/ruby/test_ruby_3_4.py
tests/integration/unit_test/test_unit_test_ruby3_4.py

Ruby 3.4 is coming soon: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-future
Add new templates for Ruby 3.4, basically replicating the templates for Ruby 3.3. Previous PR to support Ruby 3.3 here: #494
Some integration tests won't work until build images are available.

feat: add ruby3.4 support

---

al2/graalvm/11/gradle/{{cookiecutter.project_name}}/Dockerfile
al2/graalvm/11/maven/{{cookiecutter.project_name}}/Dockerfile
al2/graalvm/17/gradle/{{cookiecutter.project_name}}/Dockerfile
al2/graalvm/17/maven/{{cookiecutter.project_name}}/Dockerfile
python3.10/apigw-pytorch/cookiecutter.json
python3.10/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt
python3.11/apigw-pytorch/cookiecutter.json
python3.11/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt
python3.11/apigw-scikit/{{cookiecutter.project_name}}/app/requirements.txt
python3.11/apigw-tensorflow/{{cookiecutter.project_name}}/app/requirements.txt
python3.11/apigw-xgboost/{{cookiecutter.project_name}}/app/requirements.txt
python3.12/apigw-pytorch/cookiecutter.json
python3.12/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt
python3.13/apigw-pytorch/cookiecutter.json
python3.13/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt
python3.9/apigw-pytorch/cookiecutter.json
python3.9/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt

Bump pytorch version to 2.6.0. This newest version does not have a +cpu wheel in https://download.pytorch.org/whl/torch_stable.html so we can add it when it is released in the future. Also pinned numpy version based on what torchvision and tensorflow require.
Also fixed java al2 templates as the dockerfile was still using python3.8.

chore: bump pytorch version
