aws/aws-sam-cli-app-templates

nodejs10.x/cookiecutter-quick-start-cloudwatch-events/{{cookiecutter.project_name}}/template.yml, nodejs10.x/cookiecutter-quick-start-from-scratch/{{cookiecutter.project_name}}/template.yml, nodejs10.x/cookiecutter-quick-start-sns/{{cookiecutter.project_name}}/template.yml, nodejs10.x/cookiecutter-quick-start-sqs/{{cookiecutter.project_name}}/template.yml
=> Quickstart Fixes

java8/cookiecutter-aws-sam-eventbridge-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/model/aws.ec2/EC2InstanceStateChangeNotification.java
=> Fixing EC2 instance-id attribute on EventBridge starter app EC2InstanceStateChangeNotification

java8/cookiecutter-aws-sam-eventbridge-hello-java-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/model/aws.ec2/EC2InstanceStateChangeNotification.java, java8/cookiecutter-aws-sam-eventbridge-hello-java-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/model/aws.ec2/EC2InstanceStateChangeNotification.java
=> Adding missed import statement to EB gradle template and applying same change to maven repo

dotnetcore2.0/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md, dotnetcore2.1/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md, go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/README.md, java11/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/README.md, java11/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/README.md, java8/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/README.md, java8/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-cloudwatch-events/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-from-scratch/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-s3/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-sns/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-sqs/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-sqs/{{cookiecutter.project_name}}/template.yml, nodejs10.x/cookiecutter-quick-start-web/{{cookiecutter.project_name}}/README.md, nodejs10.x/cookiecutter-quick-start-web/{{cookiecutter.project_name}}/template.yml, nodejs12.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, nodejs8.10/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/README.md, python3.6/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md, python3.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md, python3.8/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md, ruby2.5/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/README.md
Note - I will merge this when the relevant changes are released. Do not merge this yet!
=> Update READMEs for Guided Deploy

manifest.json, python2.7/cookiecutter-aws-sam-hello-python/.gitignore, python2.7/cookiecutter-aws-sam-hello-python/README.md, python2.7/cookiecutter-aws-sam-hello-python/cookiecutter.json, python2.7/cookiecutter-aws-sam-hello-python/setup.cfg, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/.gitignore, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/README.md, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/events/event.json, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/hello_world/app.py, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/hello_world/requirements.txt, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/template.yaml, python2.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/tests/unit/test_handler.py
Keeping it around in this template repo as well until formal EOL.
=> Python2.7 Init Template

manifest.json, ruby2.7/cookiecutter-aws-sam-hello-ruby/.gitignore, ruby2.7/cookiecutter-aws-sam-hello-ruby/README.md, ruby2.7/cookiecutter-aws-sam-hello-ruby/cookiecutter.json, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/.gitignore, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/Gemfile, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/README.md, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/events/event.json, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/hello_world/Gemfile, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/hello_world/app.rb, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/template.yaml, ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/tests/unit/test_handler.rb
Dependent on aws sam cli release: v0.43.0
=> feat: ruby 2.7 templates for `sam init`

dotnetcore2.1/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/template.yaml
=> Fixing indentation issue for the .NET core 2.1 template 

ruby2.5/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock_buyer/app.rb, ruby2.5/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock_seller/app.rb, ruby2.5/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/tests/unit/test_stock_buyer.rb, ruby2.5/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/tests/unit/test_stock_checker.rb, ruby2.5/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/tests/unit/test_stock_seller.rb, ruby2.7/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock_buyer/app.rb, ruby2.7/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock_seller/app.rb, ruby2.7/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/tests/unit/test_stock_buyer.rb, ruby2.7/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/tests/unit/test_stock_checker.rb, ruby2.7/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/tests/unit/test_stock_seller.rb
Existing templates won't pass unit tests and don't follow best practices. With these changes, the examples will follow Ruby conventions and unit tests pass.
=> Ruby SFN Fixes

dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/.gitignore, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/Pipfile, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/README.md, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/cookiecutter.json, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/setup.cfg, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/tests/test_cookiecutter.py, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/build.ps1, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/events/event.json, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/src/Function.ps1, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/template.yaml, dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/test/Function.tests.ps1
*Issue #, if available:* Fixes #50 
* Added quick start template for PowerShell Lambdas
* This PR continues efforts that were originally attempted in https://github.com/awslabs/aws-sam-cli/pull/820
* I did not see a way for the SAM CLI to directly package the PowerShell zip file in the required way. So I fell back to the *AWSLambdaPSCore PowerShell module*. I think this makes sense as most PowerShell developers will be familiar with this module and packaging PowerShell lambdas with it.
* Pester is the ubiquitous test and mock framework for PowerShell.
```powershell
Describing HelloWorld Tests
[+] Should return a normal crafted return when the …
```
=> added support for powershell lambda functions

dotnetcore2.1-image/cookiecutter-aws-sam-hello-dotnet-lambda-image/{{cookiecutter.project_name}}/template.yaml, dotnetcore3.1-image/cookiecutter-aws-sam-hello-dotnet-lambda-image/{{cookiecutter.project_name}}/template.yaml, go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/template.yaml, java11-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/template.yaml, java11-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/template.yaml, java8-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/template.yaml, java8-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/template.yaml, java8.al2-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/template.yaml, java8.al2-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/template.yaml, nodejs10.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/template.yaml, nodejs12.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/template.yaml, python2.7-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml, python3.6-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml, python3.7-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml, python3.8-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml, ruby2.5-image/cookiecutter-aws-sam-hello-ruby-lambda-image/{{cookiecutter.project_name}}/template.yaml, ruby2.7-image/cookiecutter-aws-sam-hello-ruby-lambda-image/{{cookiecutter.project_name}}/template.yaml
* remove ImageConfig property comment
Look at syntax section: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-imageconfig.html
=> fix(inits): remove ImageConfig property comment

nodejs10.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/package.json, nodejs10.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json, nodejs12.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/package.json, nodejs12.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
=> Update axios Dependencies

buildspecs/buildspec-unittest-python2.7.yml, python2.7-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/hello_world/Dockerfile
Identical to https://github.com/aws/aws-sam-cli/pull/2695
=> fix: Python 2.7 get-pip.py URL

go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/Dockerfile, java8-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/Dockerfile, java8.al2-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/HelloWorldFunction/Dockerfile
Use ECR images so that we don't get docekr hub request limit issues. 
=> chore: Use ECR images

cdk-python/nodejs14.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/requirement.txt, cdk-python/python3.8/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/requirement.txt
=> add the requirement.txt file in cdk python

manifest.json
=> feat: Add use-case description to template manifest

python3.8-image/cookiecutter-ml-apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt, python3.8-image/cookiecutter-ml-apigw-scikit-learn/{{cookiecutter.project_name}}/app/requirements.txt, python3.8-image/cookiecutter-ml-apigw-tensorflow/{{cookiecutter.project_name}}/app/requirements.txt, python3.8-image/cookiecutter-ml-apigw-xgboost/{{cookiecutter.project_name}}/app/requirements.txt
Bumping pillow and tensorflow dependencies.
=> chore: Bump pillow and tensorflow dependencies for python3.8-image

python3.8-image/cookiecutter-ml-apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt, python3.8-image/cookiecutter-ml-apigw-scikit-learn/{{cookiecutter.project_name}}/app/requirements.txt, python3.8-image/cookiecutter-ml-apigw-tensorflow/{{cookiecutter.project_name}}/app/requirements.txt, python3.8-image/cookiecutter-ml-apigw-xgboost/{{cookiecutter.project_name}}/app/requirements.txt
=> chore: Bump Python 3.8 ML APIGW Pillow to 8.3.2

python3.9/cookiecutter-aws-sam-step-functions-etl-python/.gitignore, python3.9/cookiecutter-aws-sam-step-functions-etl-python/README.md, python3.9/cookiecutter-aws-sam-step-functions-etl-python/cookiecutter.json, python3.9/cookiecutter-aws-sam-step-functions-etl-python/setup.cfg, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/.gitignore, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/README.md, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/functions/etl_check/app.py, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/functions/etl_failure/app.py, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/functions/etl_success/app.py, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/statemachine/asl.json, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/template.yaml, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/tests/integration/test_state_machine.py, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/tests/requirements.txt, python3.9/cookiecutter-aws-sam-step-functions-etl-python/{{cookiecutter.project_name}}/tests/unit/test_handler.py
Template for creating a Step Functions workflow that executes a Glue Job, waits for completion, and then invokes a Lambda function on success or failure.
=> feat: Added a Glue job example for a Step Functions workflow

nodejs14.x/cookiecutter-quick-start-sqs/{{cookiecutter.project_name}}/template.yaml
*Issue #, if available: https://github.com/aws/aws-sam-cli-app-templates/issues/150
*Description of changes:
Fix NodeJs14 sqs template.
=> fix: Queue arn reference from Fn::GetAtt to !GetAtt

.github/workflows/README.md, .github/workflows/pr-labeler.yml
n/a
Adds a Github Action that auto labels PRs (similar to SAM and SAM CLI repos)
=> Chore: Auto PR Labeler

nodejs10.x/cookiecutter-quick-start-cloudwatch-events/{{cookiecutter.project_name}}/buildspec.yml, nodejs10.x/cookiecutter-quick-start-from-scratch/{{cookiecutter.project_name}}/buildspec.yml, nodejs10.x/cookiecutter-quick-start-s3/{{cookiecutter.project_name}}/buildspec.yml, nodejs10.x/cookiecutter-quick-start-sns/{{cookiecutter.project_name}}/buildspec.yml, nodejs10.x/cookiecutter-quick-start-sqs/{{cookiecutter.project_name}}/buildspec.yml, nodejs10.x/cookiecutter-quick-start-web/{{cookiecutter.project_name}}/buildspec.yml, nodejs12.x/cookiecutter-quick-start-cloudwatch-events/{{cookiecutter.project_name}}/buildspec.yml, nodejs12.x/cookiecutter-quick-start-from-scratch/{{cookiecutter.project_name}}/buildspec.yml, nodejs12.x/cookiecutter-quick-start-s3/{{cookiecutter.project_name}}/buildspec.yml, nodejs12.x/cookiecutter-quick-start-sns/{{cookiecutter.project_name}}/buildspec.yml, nodejs12.x/cookiecutter-quick-start-sqs/{{cookiecutter.project_name}}/buildspec.yml, nodejs12.x/cookiecutter-quick-start-web/{{cookiecutter.project_name}}/buildspec.yml
Resolves: https://github.com/aws/aws-sam-cli-app-templates/issues/55
=> Remove type: zip in buildspec.yml

nodejs10.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/README.md, nodejs10.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/Dockerfile, nodejs12.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/README.md, nodejs12.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/Dockerfile, nodejs14.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/README.md, nodejs14.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/Dockerfile
Adding comment about `npm ci` in case of building for production environment.
=> docs/feat: also copy package-lock.json in hello-world node dockerfiles, and add a comment about npm ci

manifest.json, tests/unit/test_json.py
please note that "useCaseName" field is now required field when updating a new app template in the  manifest.json file.
=> Update: Create Hello World Example use case from Serverless API use case in Manifest File

nodejs10.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/package.json, nodejs10.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json, nodejs10.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-buyer/package.json, nodejs10.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-checker/package.json, nodejs10.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-seller/package.json, nodejs12.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/package.json, nodejs12.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json, nodejs12.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-buyer/package.json, nodejs12.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-checker/package.json, nodejs12.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-seller/package.json, nodejs12.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/integration-tests/package.json, nodejs12.x/cookiecutter-typescript-app-template/{{cookiecutter.project_name}}/app/package.json, nodejs12.x/cookiecutter-typescript-app-template/{{cookiecutter.project_name}}/app/tsconfig.json, nodejs14.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/hello-world/package.json, nodejs14.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/package.json, nodejs14.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-buyer/package.json, nodejs14.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-checker/package.json, nodejs14.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stock-seller/package.json, tests/integration/build_invoke/build_invoke_base.py, tests/integration/unit_test/test_unit_test_dotnetcore3_1.py, tests/integration/unit_test/unit_test_base.py
=> chore: use 'samdev' only when developing locally, use 'sam' otherwise

manifest.json
Reverts aws/aws-sam-cli-app-templates#204
=> Revert "fix(dotnet6): Set .NET6 example as Hello-World"

.github/workflows/manifest-backward-compability-check.yml, .gitignore, buildspecs/buildspec-dotnetcore3.1.yml
=> feat: CI Check for Old Manifest Backward Compatibility

manifest-v2.json
#122
None of the other Step Functions Sample apps are marked as dynamic. Remove this flag in this PR. 
=> fix: Remove isDynamicTemplate from java11/cookiecutter-aws-sam-step-functions-sample-app-gradle app

python3.8-image/cookiecutter-ml-apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt, python3.9-image/cookiecutter-ml-apigw-pytorch/cookiecutter.json
N/A
Bump version of pytorch in pytorch ML templates, to resolve dependabot alerts.
=> Update pytorch version

al2/graalvm/11/maven/{{cookiecutter.project_name}}/Dockerfile, al2/graalvm/17/maven/{{cookiecutter.project_name}}/Dockerfile
=> fix: bump maven version to the latest available

dotnet6/hello-pt/{{cookiecutter.project_name}}/template.yaml
*Issue:* https://github.com/aws/aws-sam-cli/issues/4860
Just a quick fix, will address the issue on the side of `aws-sam-cli` later on
=> Quick and dirty fix for https://github.com/aws/aws-sam-cli/issues/4860

.github/workflows/build_test_invoke.yml, .github/workflows/manifest-backward-compability-check.yml, .github/workflows/manifest-v2-check.yml
N/A
Adds `merge_group` to the required Github Actions workflow checks so that a merge queue is able to trigger them.
=> feat: Added merge group triggers to required Github Action workflows

.github/workflows/build_test_invoke.yml, nodejs14.x/hello-ts-pt/README.md, nodejs16.x/hello-ts-pt/README.md, nodejs18.x/hello-ts-pt/README.md, python3.7/hello-pt/README.md, python3.7/hello-pt/{{ cookiecutter.project_name }}/README.md, python3.8/hello-pt/README.md, python3.8/hello-pt/{{ cookiecutter.project_name }}/README.md, python3.9/hello-pt/README.md, python3.9/hello-pt/{{ cookiecutter.project_name }}/README.md
#373 
Fix incorrect reference of Lambda Powertools in pt templates
=> Fix readme in powertools templates

dotnetcore3.1/cw-event/{{cookiecutter.project_name}}/template.yaml, tests/integration/base.py, tests/integration/build_invoke/build_invoke_base.py, tests/integration/build_invoke/dotnet/test_build_invoke_dotnetcore3_1.py, tests/integration/build_invoke/node/test_node_12.py, tests/integration/build_invoke/python/test_python_3_10.py, tests/integration/unit_test/test_unit_test_dotnetcore3_1.py, tests/integration/unit_test/test_unit_test_nodejs12_x.py, tests/integration/unit_test/test_unit_test_python3_10.py
N/A
Update integ base to run lint test after init
=> add lint test to integ base

java11/hello-gradle/{{cookiecutter.project_name}}/README.md, java11/hello-img-gradle/{{cookiecutter.project_name}}/README.md, java11/hello-img-maven/{{cookiecutter.project_name}}/README.md, java11/hello-maven/{{cookiecutter.project_name}}/README.md, java11/hello-pt-maven/{{cookiecutter.project_name}}/README.md, java11/step-func-gradle/{{cookiecutter.project_name}}/README.md, java11/step-func-maven/{{cookiecutter.project_name}}/README.md, java8.al2/hello-gradle/{{cookiecutter.project_name}}/README.md, java8.al2/hello-img-gradle/{{cookiecutter.project_name}}/README.md, java8.al2/hello-img-maven/{{cookiecutter.project_name}}/README.md, java8.al2/hello-maven/{{cookiecutter.project_name}}/README.md, java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/README.md, java8.al2/step-func-gradle/{{cookiecutter.project_name}}/README.md, java8.al2/step-func-maven/{{cookiecutter.project_name}}/README.md, java8/hello-gradle/{{cookiecutter.project_name}}/README.md, java8/hello-img-gradle/{{cookiecutter.project_name}}/README.md, java8/hello-img-maven/{{cookiecutter.project_name}}/README.md, java8/hello-maven/{{cookiecutter.project_name}}/README.md, java8/hello-pt-maven/{{cookiecutter.project_name}}/README.md, java8/step-func-gradle/{{cookiecutter.project_name}}/README.md, java8/step-func-maven/{{cookiecutter.project_name}}/README.md
*Issue #:* #384
I am dividing into multiple smaller PRs since these changes will touch many templates. Include in this PR:
* Java templates
=> Replace cloudformation cli with sam cli in Readme files - Java templates

al2/go/step-func/{{cookiecutter.project_name}}/README.md, dotnet5/hello-img/{{cookiecutter.project_name}}/README.md, dotnet6/cw-event/{{cookiecutter.project_name}}/README.md, dotnet6/hello-ps/{{cookiecutter.project_name}}/README.md, dotnet6/scratch/{{cookiecutter.project_name}}/README.md, dotnet6/sqs/{{cookiecutter.project_name}}/README.md, dotnet6/web/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/cw-event/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/hello-img/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/hello-ps/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/hello/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/s3/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/scratch/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/sns/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/sqs/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/step-func/{{cookiecutter.project_name}}/README.md, dotnetcore3.1/web/{{cookiecutter.project_name}}/README.md, go1.x/step-func/{{cookiecutter.project_name}}/README.md, ruby2.7/hello-img/{{cookiecutter.project_name}}/README.md, ruby2.7/hello/{{cookiecutter.project_name}}/README.md, ruby2.7/step-func/{{cookiecutter.project_name}}/README.md
*Issue #:* #384
I am dividing into multiple smaller PRs since these changes will touch many templates. Include in this PR:
* AL2
* .NET
* Ruby
* Go
=> Replace cloudformation cli with sam cli in Readme files

al2/go/response-streaming/.gitignore, al2/go/response-streaming/cookiecutter.json, al2/go/response-streaming/setup.cfg, al2/go/response-streaming/{{cookiecutter.project_name}}/README.md, al2/go/response-streaming/{{cookiecutter.project_name}}/hello/go.mod, al2/go/response-streaming/{{cookiecutter.project_name}}/hello/go.sum, al2/go/response-streaming/{{cookiecutter.project_name}}/hello/main.go, al2/go/response-streaming/{{cookiecutter.project_name}}/hello/main_test.go, al2/go/response-streaming/{{cookiecutter.project_name}}/template.yaml, manifest-v2.json, tests/integration/build_invoke/test_build_invoke_go1_x.py, tests/integration/unit_test/test_unit_test_go1_x.py
N/A
Mostly copied https://github.com/aws/aws-sam-cli-app-templates/pull/397
=> Go template for response streaming

python3.10/apigw-pytorch/cookiecutter.json, python3.10/apigw-pytorch/{{cookiecutter.project_name}}/README.md, python3.10/apigw-scikit/cookiecutter.json, python3.10/apigw-scikit/{{cookiecutter.project_name}}/README.md, python3.10/apigw-tensorflow/cookiecutter.json, python3.10/apigw-tensorflow/{{cookiecutter.project_name}}/README.md, python3.10/apigw-xgboost/cookiecutter.json, python3.10/apigw-xgboost/{{cookiecutter.project_name}}/README.md, python3.10/efs/cookiecutter.json, python3.10/efs/{{cookiecutter.project_name}}/README.md, python3.10/event-bridge-schema/cookiecutter.json, python3.10/event-bridge-schema/{{cookiecutter.project_name}}/README.md, python3.10/event-bridge/cookiecutter.json, python3.10/event-bridge/{{cookiecutter.project_name}}/README.md, python3.10/hello-img/cookiecutter.json, python3.10/hello-img/{{cookiecutter.project_name}}/README.md, python3.10/hello-pt/cookiecutter.json, python3.10/hello-pt/{{ cookiecutter.project_name }}/README.md, python3.10/hello/cookiecutter.json, python3.10/hello/{{cookiecutter.project_name}}/README.md, python3.10/step-func-conn/cookiecutter.json, python3.10/step-func-conn/{{cookiecutter.project_name}}/README.md, python3.10/step-func-etl/cookiecutter.json, python3.10/step-func-etl/{{cookiecutter.project_name}}/README.md, python3.10/step-func/cookiecutter.json, python3.10/step-func/{{cookiecutter.project_name}}/README.md, python3.10/web-conn/cookiecutter.json, python3.10/web-conn/{{cookiecutter.project_name}}/README.md
*Issue:* Since this one is minor, I didn't create an issue for this
Changes focus on making bash scripts in Python documentation more consistent. Separated from #385, similar to #406.
=> Make bash scripts for Python 3.10 projects more consistent

python3.9/apigw-pytorch/cookiecutter.json, python3.9/apigw-pytorch/{{cookiecutter.project_name}}/README.md, python3.9/apigw-scikit/cookiecutter.json, python3.9/apigw-scikit/{{cookiecutter.project_name}}/README.md, python3.9/apigw-tensorflow/cookiecutter.json, python3.9/apigw-tensorflow/{{cookiecutter.project_name}}/README.md, python3.9/apigw-xgboost/cookiecutter.json, python3.9/apigw-xgboost/{{cookiecutter.project_name}}/README.md, python3.9/efs/cookiecutter.json, python3.9/efs/{{cookiecutter.project_name}}/README.md, python3.9/event-bridge-schema/cookiecutter.json, python3.9/event-bridge-schema/{{cookiecutter.project_name}}/README.md, python3.9/event-bridge/cookiecutter.json, python3.9/event-bridge/{{cookiecutter.project_name}}/README.md, python3.9/hello-img/cookiecutter.json, python3.9/hello-img/{{cookiecutter.project_name}}/README.md, python3.9/hello-pt/cookiecutter.json, python3.9/hello-pt/{{ cookiecutter.project_name }}/README.md, python3.9/hello/cookiecutter.json, python3.9/hello/{{cookiecutter.project_name}}/README.md, python3.9/step-func-conn/cookiecutter.json, python3.9/step-func-conn/{{cookiecutter.project_name}}/README.md, python3.9/step-func-etl/cookiecutter.json, python3.9/step-func-etl/{{cookiecutter.project_name}}/README.md, python3.9/step-func/cookiecutter.json, python3.9/step-func/{{cookiecutter.project_name}}/README.md, python3.9/web-conn/cookiecutter.json, python3.9/web-conn/{{cookiecutter.project_name}}/README.md, requirements.txt
*Issue:* Since this one is minor, I didn't create an issue for this
Changes focus on making bash scripts in Python documentation more consistent. Separated from #385, similar to #406.
=> Make bash scripts for Python 3.9 projects more consistent

al2/dotnet7-aot/hello/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, al2/dotnet7-aot/hello/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj, dotnet6/cw-event/{{cookiecutter.project_name}}/src/CloudWatchEventSource/CloudWatchEventSource.csproj, dotnet6/cw-event/{{cookiecutter.project_name}}/test/CloudWatchEventSource.Tests/CloudWatchEventSource.Tests.csproj, dotnet6/hello-img/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, dotnet6/hello-img/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj, dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, dotnet6/hello-pt/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj, dotnet6/hello/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj, dotnet6/hello/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj, dotnet6/scratch/{{cookiecutter.project_name}}/src/ScratchLambda/ScratchLambda.csproj, dotnet6/scratch/{{cookiecutter.project_name}}/test/ScratchLambda.Tests/ScratchLambda.Tests.csproj, dotnet6/sns/{{cookiecutter.project_name}}/src/SNSEventSource/SNSEventSource.csproj, dotnet6/sns/{{cookiecutter.project_name}}/test/SNSEventSource.Tests/SNSEventSource.Tests.csproj, dotnet6/sqs/{{cookiecutter.project_name}}/src/SQSEventSource/SQSEventSource.csproj, dotnet6/sqs/{{cookiecutter.project_name}}/test/SQSEventSource.Tests/SQSEventSource.Tests.csproj, dotnet6/step-func/{{cookiecutter.project_name}}/functions/StockBuyer/StockBuyer.csproj, dotnet6/step-func/{{cookiecutter.project_name}}/functions/StockChecker/StockChecker.csproj, dotnet6/step-func/{{cookiecutter.project_name}}/functions/StockSeller/StockSeller.csproj
Updated AWS SDK and Powertools package dependencies for all .NET templates
Powertools Logging utility now supports Lambda Advanced Logging feature. 
=> chore(deps): bumping .NET and Powertools packages

nodejs14.x/hello-img/{{cookiecutter.project_name}}/hello-world/package.json, nodejs14.x/hello/{{cookiecutter.project_name}}/hello-world/package.json, nodejs16.x/hello-img/{{cookiecutter.project_name}}/hello-world/package.json, nodejs16.x/hello/{{cookiecutter.project_name}}/hello-world/package.json, nodejs18.x/full-stack/{{cookiecutter.project_name}}/frontend/package.json, nodejs18.x/hello-img/{{cookiecutter.project_name}}/hello-world/package.json, nodejs18.x/hello/{{cookiecutter.project_name}}/hello-world/package.json, nodejs20.x/full-stack/{{cookiecutter.project_name}}/frontend/package.json, nodejs20.x/hello-img/{{cookiecutter.project_name}}/hello-world/package.json, nodejs20.x/hello/{{cookiecutter.project_name}}/hello-world/package.json
Upgrade Axios version to at least 1.6.0 to fix security issue with past axios versions
=> Axios version bump to 1.6.0

CODEOWNERS
N/A
Remove SBT team from CODEOWNERS file
=> chore: remove SBT team from CODEOWNERS
